<?php
/**
 * @file
 * Code for the TI AMG FW Basicpage Ads feature.
 */

include_once 'ti_amg_fw_basicpage_ads.features.inc';

/**
 * Implements hook_tgx_config_zone_NODE_TYPE_alter().
 */
function ti_amg_fw_basicpage_ads_tgx_config_zone_page_alter(&$settings, $node) {
  $channel = arg(0, request_path());
  $sub_channel = arg(1, request_path());
  if ($channel == 'promo') {
  	if ($sub_channel == 'events') {
        $zone = 'events/main';
      }
      else {
        $zone = 'flat_pages';
      }
  }
  $settings['zone_value'] = $zone;
}
