<?php

$conf['install_profile'] = 'standard';
$conf['master_version'] = 2;

$conf['master_modules']['local'] =
$conf['master_modules']['dev'] =
$conf['master_modules']['qa'] =
$conf['master_modules']['prod'] = array(
// Contrib.
  'admin_menu',
  'admin_menu_toolbar',
  'breakpoints',
  'brightcove',
  'brightcove_field',
  'module_filter',
  'cdn',
  'ckeditor',
  'colorbox',
  'context',
  'context_ui',
  'context_condition_theme',
  'ctools',
  'colorbox',
  'current_search',
  'date',
  'date_migrate',
  'date_api',
  'date_popup',
  'date_views',
  'facetapi',
  'features',
  'feeds',
  'fences',
  'field_group',
  'entity',
  'entitycache',
  'entityreference',
  'entity_token',
  'fast_404',
  'hierarchical_select',
  'hs_taxonomy',
  'libraries',
  'menu_block',
  'menu_block_export',
  'metatag',
  'metatag_context',
  'metatag_opengraph',
  'metatag_panels',
  'metatag_views',
  'metatag_twitter_cards',
  'migrate',
  'migrate_ui',
  'migrate_d2d',
  'nat',
  'node_convert',
  'page_manager',
  'panels',
  'panels_mini',
  'pathauto',
  'pathcache',
  'picture',
  'publication_date',
  'redirect',
  'scheduler',
  'search_api_facetapi',
  'securepages',
  'simplehtmldom',
  'state_machine',
  'state_flow',
  'state_flow_schedule',
  'strongarm',
  'subpathauto',
  'syslog',
  'taxonomy_csv',
  'tealium',
  'token',
  'term_ref_autocomplete',
  'textformatter',
  'textformatter_contrib',
  'jquery_update',
  'views',
  'views_content',
  'xmlsitemap',
  'xmlsitemap_node',
  'xmlsitemap_engines',
  'purge',
  'skyword',
  'nodequeue',

// UI modules.
  'diff',
  'token_tweaks',

// LSG Modules.
  'ti_lsg_devel',

// Prevent dcms js alerts.
  'prevent_js_alerts',

// Voting api and five star.
  'votingapi',
  'fivestar',

// AMG Custom.
  'ti_amg_fw_articles_views',
  'ti_amg_fw_backend_search',
  'ti_amg_fw_blogs_views',
  'ti_amg_fw_custom',
  'ti_amg_fw_image_styles',
  'ti_amg_fw_migrate_fwxcontent',
  'ti_amg_fw_permissions',
  'ti_amg_fw_toc_context',
  'ti_amg_fw_toc_view',
  'ti_amg_fw_hat',
  'ti_amg_ads',
  'ti_amg_fw_nativo',
  'ti_amg_fw_node_convert',
  'ti_amg_fw_generic_page_views',
  'ti_amg_fw_ckeditor_full_profile',
  'ti_amg_fw_homepage_views',
  'ti_amg_fw_homepage_context',
  'ti_amg_fw_channel_landing_page_views_feature',
  'ti_amg_fw_person_views',
  'ti_amg_fw_person_context',
  'ti_amg_fw_person_node_form_context',
  'ti_amg_fw_slideshow_context',
  'ti_amg_fw_mobile_context',
  'ti_amg_fw_mobile_blocks',
  'ti_amg_fw_mobile_contexts',
  'ti_amg_fw_partner_feed',
  'ti_amg_fw_brightcove_settings',
// 'ti_amg_fw_mobile_menu',.
  'ti_amg_fw_mobile_homepage_views',
  'ti_amg_fw_recipe_themes_views',
  'ti_amg_fwrd_gnews_sitemap',
  'ti_amg_fwrd_gallery',
  'ti_amg_fw_recipe_rating_feeds',
  'ti_amg_fw_search',
  'ti_amg_fw_search_config',
  'ti_amg_fw_search_context',
  'ti_amg_fw_sitemap',
  'ti_amg_fw_recipe_finder',
  'ti_amg_fw_redirect',
  'ti_amg_fw_mobile_recipe_finder',
  'ti_amg_fw_mobile_recipe_finder_results',
// 'ti_amg_fw_main_menu',.
  'ti_amg_fw_page_sharing_social',
  'ti_amg_fw_page_share_social_context',
  'ti_amg_fw_outbrain',
  'ti_amg_fw_image_xmp',
  'ti_amg_fw_recipe_parsing',
  'ti_amg_fw_comscore',
  'new_relic_ti',
  'ti_amg_fw_sponsor_logo_campaign',
  'jquery_throttle',

// DCMS Content Types.
  'ti_contentType_field_base',
  'ti_amp_notifier',
  'ti_article_content_type',
  'ti_video_content_type',
  'ti_amg_fw_place_content_type',
  'ti_tout_content_type',
  'ti_image_content_type',
  'ti_gallery_content_type',
  'ti_recipe_content_type',
  'ti_person_content_type',
  'ti_basicpage_content_type',

// FoodandWine Content Types.
'ti_amg_fw_base_components',
'ti_amg_fw_article',
'ti_amg_fw_category',
'ti_amg_fw_clp_content_type',
'ti_amg_fw_gallery',
'ti_amg_fw_image',
'ti_amg_fw_recipe',
'ti_amg_fw_video',
'ti_amg_fw_taxonomy',
'ti_amg_fw_blog_content_type',
'ti_amg_fw_homepage_content_type',
'ti_channel_landing_responsive_content_type',
'ti_amg_fw_featured_directory_content_type',
'ti_amg_fw_partner_feed_content_type',
'ti_amg_fw_sub_menu_settings_content_type',
'ti_amg_fw_newsletter',

// FoodandWine Layouts.
  'ti_amg_fw_articles_contexts',
  'ti_amg_fw_contexts',
  'ti_amg_fw_blogs_contexts',
  'ti_amg_fw_theme_settings',
  'ti_amg_fw_generic_page_context',
  'ti_amg_fw_channel_landing_page_context_feature',
  'ti_amg_fw_recipe_themes_contexts',
  'ti_amg_fw_recipes_contexts',
  'ti_amg_fw_swoopad_context',
  'ti_amg_fw_partner_blog_contexts',
  'ti_amg_fw_partner_blog_context_mobile',

// FoodandWine TextFormats.
  'ti_amg_fw_text_formats',
  'ti_amg_fw_caching',

// DCMS Modules.
  'ti_caas_backfill',
  // Cache Clear Form
  'ti_cache_control',
  'ti_content_type_manager',
  'ti_udo',
  'ti_nativo_tokens',
  'ti_editorial_ckeditor_plugins',
  'ti_optimizely',
   // Ckeditor plugins
  'ti_editorial_ckeditor_profiles',
// FoodandWine Devel.
  'ti_amg_fw_devel',
  'ti_amg_tl_cache',
  'ti_amg_fw_mm_config',
  'ti_amg_fw_omniture',
  'ti_amg_fw_video_landing_page_content_type',
  'ti_amg_fw_tout_views',
  'ti_amg_fw_video_detail',
  'ti_amg_fw_video_detail_contexts',
  'ti_amg_fw_video_views',
  'ti_amg_fw_video_landing_page_contexts',
  'ti_amg_fwrd_article_contexts',
  'ti_amg_fwrd_person_contexts',
  'ti_amg_fw_video_landing_page_views',
  'ti_microsite_entity',
// FoodandWine Redesign Content Type.
  'ti_home_page_responsive_content_type',
// FoodandWine Redesign Custom Modules.
  'ti_amg_fwrd_custom',
  'ti_amg_fwrd_recipe',
  'ti_amg_fwrd_homepage',
  'ti_amg_fwrd_landing_page',
  'ti_amg_fwrd_feature',
  'ti_amg_fwrd_person',
  'ti_amg_fwrd_generic_page',
  'ti_amg_fwrd_video',
  'ti_amg_fwrd_video_landing',
  'ti_amg_fwrd_category',
// FoodandWine Redesign Feature Modules.
  'ti_amg_fwrd_recipe_contexts',
  'ti_amg_fwrd_homepage_contexts',
  'ti_amg_fwrd_channel_landing_contexts',
  'ti_amg_fwrd_feature_contexts',
  'ti_amg_fwrd_gallery_contexts',
  'ti_amg_fwrd_video_contexts',
  'ti_amg_fwrd_video_landing_contexts',
  'ti_amg_fwrd_search',

   // Pronto Json modules.
  'ti_pronto_field_formatters',
  'pronto_component_author',
  'pronto_component_body',
  'pronto_component_category',
  'pronto_component_date',
  'pronto_component_related',
  'pronto_component_tags',
  'pronto_component_title',
  'pronto_component_brightcove',
  'pronto_component_url',
  'pronto_component_image',
  'pronto_component_text',
  'pronto_component_social_share',
  'pronto_component_entityreference',
  'pronto_component_taxonomy',
  'pronto_component_metatag',
  'pronto_component_list',
  'pronto_component_image_rights',
  // Pronto Custom Modules.
  'ti_amg_fw_pronto_component_author_entity',
  'ti_amg_fw_pronto_component_body',
  'ti_amg_fw_pronto_component_image',
  'ti_amg_fw_pronto_component_video',
  'ti_amg_fw_pronto_component_field_collection',
  'ti_amg_fw_pronto_component_recipe_time',
  'ti_amg_fw_pronto_component_title',
  'ti_amg_fw_pronto_component_video_embed',
  'ti_amg_fw_pronto_component_itemhash',
  'ti_amg_fw_content_sharing',
  'ti_pronto_caas_importer',

    // Schema.org.
  'ti_schema_org',
  'ti_schema_org_jsonld_author',
  'ti_schema_org_jsonld_date',
  'ti_schema_org_jsonld_entityreference',
  'ti_schema_org_jsonld_image',
  'ti_schema_org_jsonld_publisher',
  'ti_schema_org_jsonld_text',
  'ti_schema_org_jsonld_video',

  // Timeinc Advertising Module.
  'timeinc_advertising',
  'ti_amg_fw_article_ads',
  'ti_amg_fw_category_ads',
  'ti_amg_fw_common_ads_settings',
  'ti_amg_fw_gallery_ads',
  'ti_amg_fw_blog_ads',
  'ti_amg_fw_category_pagination_ads',
  'ti_amg_fw_channel_landing_responsive_ads',
  'ti_amg_fw_homepage_responsive_ads',
  'ti_amg_fw_parnter_page_ads',
  'ti_amg_fw_person_ads',
  'ti_amg_fw_recipe_ads',
  'ti_amg_fw_tag_page_ads',
  'ti_amg_fw_video_ads',
  'ti_amg_fw_video_landingpage_ads',
  'ti_amg_fw_basicpage_ads',
  'ti_amg_fw_vertical_gallery_ads',
  'ti_amg_fw_search_page_ads',
  'ti_amg_fw_legacy_basicpage_ads',
  'ti_amg_fw_legacy_channel_landing_page_ads',
  'ti_amg_fw_legacy_misc_page_ads',
  'ti_amg_fwrd_notification',
  'ti_mm_fallthrough_components',
  // TimeINC Third Party Panel Plagin.
  'timeinc_third_party_panel_plugin',
  'editorial_ecommerce_workflow',

  // Segment.
  'segmentio',

  // TimeINC DCMS XMLSitemap Module.
  'timeinc_xmlsitemap',
  // TI AMG FW XMLSitemap Views Module.
  'ti_amg_fw_xml_sitemap_views',
  // TI AMG FW XMLSitemap Field Collection Field Formatter Module.
  'xmlsitemap_fieldcollection_formatter',
  'ti_amg_fw_springboard_article',
  // Moscow Mule Data Layer
  'ti_content_api',
  'ti_content_api_config',
  'ti_mm_editor_preview',
);

$conf['master_modules']['local'] = array_merge($conf['master_modules']['local'], array(
// Devel and _ui modules.
  'coder',
  'views_ui',
  'feeds_ui',
  'field_ui',
  'stage_file_proxy',
  'devel',
));

$conf['master_modules']['dev'] = array_merge($conf['master_modules']['dev'], array(
// Devel and _ui modules.
  'coder',
  'views_ui',
  'memcache',
  'feeds_ui',
  'field_ui',
  'queue_ui',
  'stage_file_proxy',
  'devel',
));

$conf['master_modules']['qa'] = array_merge($conf['master_modules']['qa'], array(
// Devel and _ui modules.
  'context_ui',
  'feeds_ui',
  'field_ui',
  'migrate_ui',
  'views_ui',
  'ti_amg_fw_web_services',
  'stage_file_proxy',
  // Moscow Mule Data Layer
  'ti_content_api_config',
));
